### PR TITLE
Set application_id in session when the token is set

### PR DESCRIPTION
**Pull request by fc**
Refer to #72 for details

### CODE REVIEW

**Comment by fc** [comment]
also added the safe callback calls for the WebRTC callbacks #29

**Comment by soulfly** [comment]
I'm not sure about this logic

```
 config.creds.appId = params.jid.match(/^\d+-(\d+)@.*$/)[1];
 this.service.getSession().application_id = config.creds.appId;
```

because you can override the appid value in a case when you use QB.init(appId, key, secret, config) which is not good.

What I have in my mind is to allow to call QB.init(token, appId);

**Comment by fc** [comment]
Yeah - you're right, it is a hack.  I like your suggestion is better.  Two things to consider for your suggestion: it would break backwards compatibility (if it matters.. not sure how long this has been a bug) and updating documentation (aghh).

You mean it could override the appId with the config parameter, correct?  If that's the case, an alternative suggestion where only the application_id is set, not pretty haha:

```
this.service.getSession().application_id =  params.jid.match(/^\d+-(\d+)@.*$/)[1];
```

**Comment by soulfly** [comment]
Released 1.17.1

http://quickblox.com/developers/Javascript#Framework_changelog

**Comment by soulfly** [comment]
Changes with WebRTC will be in our next release because we are preparing some more updates.

**Comment by soulfly** [comment]
//it would break backwards compatibility 

no, you can still use QB.init(sessionToken), so both variants are valid

**Pull request closed without merging**
