### PR TITLE
Gh pages.listeners

### PR DESCRIPTION
**Pull request by Vladlukhanin**
Proposed changes for version 2.1.5
- Added **onReconnectFailedListener** for catching authentication fail;
- Added **onInvalidEventsListener** for information on ignore (some exceptions);
- Added property **recipient_id** for the message object (message.recipient_id) in **onMessageListener** (only for forwarded messages);

### CODE REVIEW

**Comment by Vladlukhanin** [comment]
- Added **onReconnectFailedListener** for catching  authentication fail
- Added **onIgnoredListener** for information on ignore (some exceptions)
- Added property **recipient_id** for message object (message.recipient_id) in **onMessageListener** (only for forwarded messages)

**Comment by soulfly** [comment]
What is 'onIgnoredListener' ?

**Comment by Vladlukhanin** [comment]
When recalling the 'onAccept', 'onReject' or 'onStop' they listeners ignore their repeated signals and show console.warn("Ignore 'onAccept', the session( " + sessionID + " ) has invalid state.") for example. **onIgnoredListener** need for synchronize video/audio calls between different browsers (or more then one tabs) for same user.

**Comment by soulfly** [comment]
We have to think about better name for this listener

**Comment by Vladlukhanin** [comment]
Ok, will be renaming before merging

**Comment by soulfly** [comment]
Ok, you can merge

**Pull request merged**
