### PR TITLE
Removed depricated QBLocation module

### PR DESCRIPTION
**Pull request by dimaspirit**
*Make sure that you wrote the tests for your proposed changes and the existing test was success.*

**Made/Proposed changes:**
- Remove QBLocation (use Custom Object instead of QBLocation)
- Remove a spec for this module.

**How should this be manually tested?**

**Does the documentation need an update?**
Yes

_From version 2.6.0 SDK doesn't contain qbLocation.
Instead of you can use Custom Object (https://quickblox.com/developers/Sample-customobjects-javascript#Adding_a_Custom_Data_structure_to_your_application). It's more powerful and customizes functionality._

### CODE REVIEW

**Review by Vladlukhanin — APPROVED** [review]

**Review by IegorKozakov — APPROVED** [review]

**Comment by soulfly** [comment]
Why did you comment Push Notifications spec?

**Comment by dimaspirit** [comment]
@soulfly check March 28, 2017 in QB server Skype room.
I got ` {"code":500,"status":"500 Internal Server Error",` when make a request to https://api.quickblox.com/events/15348478/status.json
So, we created task for server SER-1190

**Comment by dimaspirit** [comment]
So I hide this specs and waiting will get a fix of this issue.

**Comment by soulfly** [comment]
I see your request about **https://api.quickblox.com/events/15348478/status.json** spec only. Why we need to comment ALL push specs? Why can't we comment only this one?

**Comment by dimaspirit** [comment]
@soulfly reworked

**Review by soulfly — APPROVED** [review]
approved

**Pull request merged**
