### PR TITLE
Added stickers

### PR DESCRIPTION
**Pull request by dehimb**

### CODE REVIEW

**Comment by dimaspirit** [comment]
We use only https, so please will fix it. [screen](http://dl2.joxi.net/drive/2016/04/05/0005/4037/335813/13/045ebbdcde.jpg)

**Comment by dimaspirit** [comment]
When we try to upload media, preload gif shows incorrect. [screen](http://dl2.joxi.net/drive/2016/04/05/0005/4037/335813/13/704a216acb.jpg)

**Comment by dimaspirit** [comment]
What do I do wrong? [screen](http://dl2.joxi.net/drive/2016/04/05/0005/4037/335813/13/0cc778476a.jpg)

**Comment by dehimb** [comment]
> What do I do wrong?

@dimaspirit 
Now we can't reproduce this error. Can you provide more information how to reproduce it?

**Comment by dimaspirit** [comment]
1. Could you change into a secure connection http://joxi.ru/4Ak3VqGuM7JBaA ?
   Example, without: [Rock](http://static.stickerpipe.com/sticker/casualpack31/tab_icon_hdpi.png?scl=19&sh=XqB4e_V5OZPUlb4H_X5Uqw), with [Rock](https://static.stickerpipe.com/sticker/casualpack31/tab_icon_hdpi.png?scl=19&sh=XqB4e_V5OZPUlb4H_X5Uqw)

**Comment by dimaspirit** [comment]
One more critical issue - http://joxi.ru/E2pvYqbSB6o6qr when I click on plus

**Comment by dehimb** [comment]
@dimaspirit 
We fixed this issues. Please, check it

**Comment by dimaspirit** [comment]
@dehimb, the last thing is secure HTTP. Please use https for the stickers. 
http://joxi.net/4Ak3VqGuM7JBaA

**Comment by dimaspirit** [comment]
@dehimb, the last thing is secure HTTP. Please use https for the stickers. 
http://joxi.net/4Ak3VqGuM7JBaA

**Comment by dehimb** [comment]
@dimaspirit now we use https. Please, clear local storage

**Pull request merged**
